#! /bin/bash

cat MESSAGE;

while true;
do
echo 'Dice to roll';
input dice;

echo 'Advantage or Disadvantage(Advantage/Disadvantage/Nothing)';
input adv;

echo 'modifiers?(1/-1)';
input modifier;

if (adv == 'N');
echo '(($RANDOM % dice + modifier))';
exit 1;
#cant remember bash syntax :D

done


